# Generated by Django 5.2 on 2025-06-10 17:09

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclassification',
            name='image',
            field=models.ImageField(upload_to='classified_images', validators=[blog.models.validate_image_format]),
        ),
    ]
