# Generated by Django 5.2 on 2025-05-03 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GardenFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_garden.flower')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_garden.virtualgarden')),
            ],
            options={
                'unique_together': {('garden', 'flower')},
            },
        ),
    ]
