# Generated by Django 5.2 on 2025-05-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_garden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveIntegerField(default=0)),
                ('unlocked', models.BooleanField(default=False)),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtual_garden.flower')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='virtual_garden.virtualgarden')),
            ],
            options={
                'unique_together': {('garden', 'slot_index')},
            },
        ),
    ]
