# Generated by Django 5.2 on 2025-05-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_garden', '0002_gardenslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
