# Generated by Django 5.2 on 2025-06-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_garden', '0003_flower_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenslot',
            name='pos_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gardenslot',
            name='pos_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
