# Generated by Django 5.2 on 2025-06-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_garden', '0004_gardenslot_pos_x_gardenslot_pos_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenslot',
            name='pos_x',
            field=models.FloatField(blank=True, help_text='Pozitia X ca procent (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='gardenslot',
            name='pos_y',
            field=models.FloatField(blank=True, help_text='Pozitia Y ca procent (0-100)', null=True),
        ),
    ]
