# Generated by Django 5.2 on 2025-06-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_garden', '0005_alter_gardenslot_pos_x_alter_gardenslot_pos_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenslot',
            name='pos_x',
            field=models.FloatField(blank=True, help_text='Pozitia X ca procent', null=True),
        ),
        migrations.AlterField(
            model_name='gardenslot',
            name='pos_y',
            field=models.FloatField(blank=True, help_text='Pozitia Y ca procent', null=True),
        ),
    ]
